package org.example.Lab5.MainTask1;

public enum AvailableFunctions {
    SHOW_TEXT_FROM_FILE,
    FILL_FILE_MANUALLY,
    REMOVE_EXTRA_SPACES,
    FIRST_LATTER_BECOME_LAST,
    REMOVE_EXTRA_SPACES_AND_FIRST_LATTER_BECOME_LAST_AND_SAVE_TO_FILE,
    ADD_NEW_TEXT_TO_FILE,
    REPLACE_TEXT_IN_FILE
}
